update instructions how to get started (installation of your Mac) (DEV-2215)
dasch-swiss/dsp-docs pull request #88
Opened 2023-05-26 18:37 UTC by jnussbaum

resolves DEV-2215

2023-05-30 12:49 UTC, flavens requested changes
Here are my suggestions for you. I would use the same turn of phrase everywhere and add colons at the end of each sentence that precedes a command line.

2023-05-30 12:49 UTC, flavens commented on docs/developers/getting-started.md
> +restart DSP-API,
I would add the link to the DSP-API doc

2023-05-30 12:49 UTC, flavens commented on docs/developers/getting-started.md
> +create `rosetta.json` and upload `rosetta.xml` again,
I would add the link to the DSP-TOOLS doc

2023-05-30 13:51 UTC, danielasubotic requested changes
see the comments

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +| DSP-API   | The core of our software stack, the RDF database that offers an access via API                 |
I would go with this suggestion from Flavie: The core of our software stack is the RDF database that offers access via API.

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +| DSP-APP   | The web application that allows you to view and edit data in your browser                      |
This is the web application that allows you to view, add and edit data to your research project

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +Unfortunately, Windows is not supported.
Windows is not supported.
-> remove "unfortunately"

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +  [second paragraph](#install-dsp-instructions-for-developers)
As Flavie mentioned already, for me it is not clear which are the first and the second paragraph. Where do they start? I would like to see how they are named without having to click on the link.

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +## Install DSP: Instructions for users
Install DSP: Instructions for Researchers and Data Stewards
-> I would call it exactly the same as in text

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +- Researchers, data stewards, and other users can take the shortcut described in the
Which other users? I would remove that and only talk about researchers and data stewards.

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +### XCode command line tools
Please add some numbers to indicate that this is the first step: 1. XCode command line tools

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +### Docker Desktop
Please add some numbers to indicate that this is the second step: 2.  Docker Desktop

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +### Python
Please add some numbers to indicate that this is the third step: 3. Python

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +### DSP-TOOLS
Please add some numbers to indicate that this is the fourth step: 4. DSP-TOOLS

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +### DSP-API and DSP-APP
Please add some numbers to indicate which step that is.

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +### Try out our test project *Rosetta*
Please add some numbers to indicate which step that is.

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +### XCode command line tools
Please add some numbers to indicate which step that is.

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +### Homebrew
Please add some numbers to indicate which step that is.

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +### Python
Please add some numbers to indicate which step that is.

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +### Docker Desktop
Please add some numbers to indicate which step that is.

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +### Git
Please add some numbers to indicate which step that is.

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +### OpenJDK 17
Please add some numbers to indicate which step that is.

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +### sbt
Please add some numbers to indicate which step that is.

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +### Node.js, npm, and Angular
Please add some numbers to indicate which step that is.

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +### yarn
Please add some numbers to indicate which step that is.

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +### DSP-API and DSP-APP
Please add some numbers to indicate which step that is.

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +### DSP-TOOLS
Please add some numbers to indicate which step that is.

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +From time to time, you have to upgrade DSP-TOOLS to the latest version.
I would add something like that: Please check every time before using DSP-TOOLS that you have the newest version of DSP-Tools running.

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +That's it, already!
As Flavie mentioned, I would reformulate it as well.

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +If you want to contribute to the development of DSP, you have to install a few more dependencies.
I would rephrase it something like: ...., you need to install a few additional dependencies.

2023-05-30 13:51 UTC, danielasubotic commented on docs/developers/getting-started.md
> +Angular can be installed with
Generally, I would use more the active voice than the passive voice and use it consistently throughtout the guide. Here it is passive and if you go to the yarn section, it is: Install yarn with

2023-05-30 15:21 UTC, jnussbaum commented on docs/developers/getting-started.md
> +- Researchers, data stewards, and other users can take the shortcut described in the
I think it's important to address the "other users" explicitly. Not everyone who reads our docs is either a researcher or a data steward. There might be other groups of users.

2023-05-30 15:23 UTC, jnussbaum commented
@flavens @danielasubotic : Thanks for your feedback 👍  I implemented a lot of it. How do you like it now?

2023-05-31 07:54 UTC, flavens approved these changes

2023-05-31 08:56 UTC, merged