chore: tidy up (DEV-2248)
dasch-swiss/dsp-docs pull request #89
Opened 2023-06-07 08:49 UTC by jnussbaum

resolves DEV-2248

2023-06-07 21:19 UTC, danielasubotic requested changes
Please see my comments. Thx for improving this page!

2023-06-07 21:19 UTC, danielasubotic commented on docs/index.md
> +Welcome to DaSCH, the Swiss National Data and Service Center for the Humanities (DaSCH)!
Our correct name is: DaSCH - Swiss National Data and Service Center for the Humanities
So you could probably change this sentence to something like:
Since 2021, DaSCH has operated as a national research data infrastructure primarily funded by the Swiss National Science Foundation (SNSF).

2023-06-07 21:19 UTC, danielasubotic commented on docs/index.md
> +on the [developers page](developers/getting-started).
I would leave the sections "for researchers", "for developers" and "for the community".  In order for that the "about us" page needs to be adapted as well.

2023-06-08 06:59 UTC, jnussbaum commented on docs/index.md
> +on the [developers page](developers/getting-started).
I want to keep it as minimalistic as possible. I don't think that the community needs to be addressed on our documentation page. We have dasch.swiss for the community.

There are only 3 things that are necessary here: 
 - our 3 tools API, APP, TOOLS
 - quick start for researchers
 - gettings started for developers (installation instruction)

Why do you thinks it's necessary to have the community page here?

2023-06-08 06:59 UTC, jnussbaum commented on docs/index.md
> +Welcome to DaSCH, the Swiss National Data and Service Center for the Humanities (DaSCH)!
done

2023-06-13 11:22 UTC, flavens requested changes

2023-06-13 11:22 UTC, flavens commented on docs/index.md
> +on the [developers page](developers/getting-started).
I would agree with Daniela. In one of your previous documentation changes, you divided the instructions between user groups (any user/developer). The purpose of this PR is to clean up the content, not to reorganize the sections. A project will be dedicated to this task.

2023-12-15 14:23 UTC, seakayone commented
Is this still a thing or can we close this PR?

2023-12-15 14:25 UTC, jnussbaum commented
> Is this still a thing or can we close this PR?

I would love to tidy up, but people always say that it's not worth it, because soon, there will be a new concept for documentation. So I didn't manage to get an Approve for this PR. So realistically, we can close it :-)

2024-01-30 09:03 UTC, merged